# Generated by Django 5.2.6 on 2025-10-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_ingrediente_ajusteinventario_movimientoinventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='costo_unitario',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='precio_paquete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio del Paquete'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='tamaño_paquete',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Tamaño del Paquete'),
        ),
    ]
