# Generated by Django 5.2.6 on 2025-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('local', 'Recoger en local'), ('domicilio', 'Envío a domicilio')], default='local', max_length=20),
        ),
    ]
