# Generated by Django 5.2.6 on 2025-10-01 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_direccion_entrega_pedido_metodo_pago_and_more'),
        ('productos', '0003_remove_producto_imagen_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.promocion'),
        ),
    ]
