# Generated by Django 5.2.6 on 2025-11-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_descuento_aplicado_pedido_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
